# Generated by Django 4.2 on 2024-04-24 16:36

from django.db import migrations, models
import django.db.models.deletion
import step2.article


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('step1', '0005_archived_article_is_content_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_file', models.FileField(help_text='Browse the file', storage=step2.article.OverWriteStorage(), upload_to=step2.article.get_file_path)),
                ('title', models.TextField(blank=True, help_text='Article title', null=True)),
                ('type_of_record', models.CharField(choices=[('article', 'article'), ('retraction', 'retraction'), ('letter to the editor', 'letter to the editor')], help_text='Select from drop down', max_length=24)),
                ('last_stage', models.CharField(choices=[('active', 'active'), ('failed', 'failed'), ('completed', 'completed')], default='active', help_text='Select from drop down', max_length=10)),
                ('note', models.TextField(default='ok', help_text='Note, warning or error note')),
                ('DOI', models.TextField(blank=True, help_text='A unique and persistent identifier', null=True)),
                ('PID', models.TextField(blank=True, help_text='A locally assign identifie', null=True)),
                ('MMSID', models.TextField(blank=True, help_text="The article's Alma identifer", null=True)),
                ('provider_rec', models.CharField(blank=True, help_text='Provider article identifier', max_length=10, null=True)),
                ('start_date', models.DateTimeField(auto_now=True, help_text='The date the article object was created')),
                ('current_date', models.DateTimeField(auto_now_add=True, help_text='The date finished the last stage')),
                ('end_date', models.DateTimeField(help_text='The data the article is staged for Alma', null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='step1.archived_article')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provsider', to='step1.providers')),
            ],
        ),
    ]
