# Generated by Django 4.2 on 2024-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_attributes',
            name='last_status',
            field=models.CharField(choices=[('active', 'active'), ('failed', 'failed'), ('completed', 'completed')], default='active', help_text='Select from drop down', max_length=10),
        ),
        migrations.AlterField(
            model_name='article_attributes',
            name='last_stage',
            field=models.IntegerField(default=2, help_text='Last stage article passed through 1-11'),
        ),
    ]
