# Generated by Django 4.2 on 2024-04-25 16:53

from django.db import migrations, models
import step2.article


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0002_article_attributes_last_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_attributes',
            name='article_file',
            field=models.FileField(help_text='Browse the file', storage=step2.article.OverWriteStorage(), upload_to=''),
        ),
    ]
