# Generated by Django 4.2 on 2024-04-25 16:59

from django.db import migrations, models
import step2.article


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0003_alter_article_attributes_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_attributes',
            name='article_file',
            field=models.FileField(help_text='Browse the file', storage=step2.article.OverWriteStorage(), upload_to=step2.article.get_file_path),
        ),
    ]
