# Generated by Django 4.2 on 2024-05-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0006_alter_archived_article_provider_and_more'),
        ('step2', '0004_alter_article_attributes_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_attributes',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archives', to='step1.archived_article'),
        ),
        migrations.AlterField(
            model_name='article_attributes',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provsider', to='step1.providers'),
        ),
    ]
