# Generated by Django 4.2 on 2024-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0005_alter_article_attributes_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unreadable_xml_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('error_msg', models.TextField()),
            ],
        ),
    ]
