# Generated by Django 4.2 on 2024-04-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_notification',
            name='applicable_to',
            field=models.TextField(default='Submission', help_text='Enter any name to indentify where this record will be used as foreign key for sending email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider_meta_data_ftp',
            name='email_notification',
            field=models.ForeignKey(blank=True, help_text='In case email notifications are required to be sent to inform status, select the email group. This is optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='step1.email_notification'),
        ),
        migrations.AlterField(
            model_name='email_notification',
            name='email_to',
            field=models.TextField(help_text='Enter list of email addresses of the receivers in this format email-1;email-2;email3;and so on;'),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_api',
            name='email_notification',
            field=models.ForeignKey(blank=True, help_text='In case email notifications are required to be sent to inform status, select the email group. This is optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='step1.email_notification'),
        ),
    ]
