# Generated by Django 4.2 on 2024-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_article_attribute',
            name='jsonified_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
