# Generated by Django 4.2 on 2024-04-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_article',
            name='jsonified_content',
        ),
        migrations.RemoveField(
            model_name='archived_article',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='archived_article',
            name='unzipped_folder_size',
        ),
        migrations.RemoveField(
            model_name='provider_model',
            name='archive_switch',
        ),
        migrations.RemoveField(
            model_name='provider_model',
            name='article_switch',
        ),
        migrations.RemoveField(
            model_name='provider_model',
            name='requirement_override',
        ),
        migrations.AlterField(
            model_name='provider_model',
            name='in_production',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='provider_model',
            name='official_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='provider_model',
            name='working_name',
            field=models.CharField(max_length=64),
        ),
    ]
