# Generated by Django 4.2 on 2024-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0002_archived_article_attribute_jsonified_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_article_attribute',
            name='unique_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
