# Generated by Django 4.2 on 2024-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0002_email_notification_applicable_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_meta_data_ftp',
            name='protocol',
            field=models.CharField(choices=[('FTP', 'FTP,'), ('SFTP', 'SFTP,')], help_text='Enter Protocol used by this FTP. i.e. FTP / SFTP', max_length=10),
        ),
    ]
