# Generated by Django 4.2 on 2024-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0002_remove_archived_article_jsonified_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider_model',
            new_name='Providers',
        ),
        migrations.RemoveField(
            model_name='provider_meta_data_api',
            name='api_switch',
        ),
        migrations.RemoveField(
            model_name='provider_meta_data_api',
            name='last_accessed_page',
        ),
        migrations.RemoveField(
            model_name='provider_meta_data_ftp',
            name='pull_switch',
        ),
        migrations.AlterField(
            model_name='archived_article',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
