# Generated by Django 4.2 on 2024-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0003_alter_provider_meta_data_ftp_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='provider_type',
            field=models.CharField(choices=[('FTP', 'FTP'), ('API', 'API')], default='FTP', max_length=4),
        ),
    ]
