# Generated by Django 4.2 on 2024-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0004_providers_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_article',
            name='is_content_changed',
            field=models.BooleanField(default=False, help_text='Flag to maintain if the existing content is changed and file_content is update'),
        ),
        migrations.AddField(
            model_name='archived_article',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Flag to maintain if the record is processed for step 2'),
        ),
    ]
