# Generated by Django 4.2 on 2024-05-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0005_archived_article_is_content_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_article',
            name='provider',
            field=models.ForeignKey(help_text='Select provider', on_delete=django.db.models.deletion.DO_NOTHING, related_name='archives', to='step1.providers'),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_api',
            name='provider',
            field=models.ForeignKey(help_text='Select Provider name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='api_provider', to='step1.providers'),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_ftp',
            name='provider',
            field=models.ForeignKey(help_text='Select Provider name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ftp_provider', to='step1.providers'),
        ),
    ]
