# Generated by Django 4.2 on 2024-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='api_meta_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
