# Generated by Django 4.2 on 2024-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_archived_article_attribute_file_name_on_ftp'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_article_attribute',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
