# Generated by Django 4.2 on 2024-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_provider_meta_data_api_api_meta_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_meta_data_api',
            name='api_meta_type',
            field=models.CharField(blank=True, choices=[('Chorus', 'Chorus'), ('CrossRef', 'CrossRef'), ('Submission', 'Submission')], max_length=20, null=True),
        ),
    ]
