# Generated by Django 4.2 on 2024-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_archived_article_attribute_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_article_attribute',
            name='file_type',
            field=models.CharField(default='tar', max_length=20),
            preserve_default=False,
        ),
    ]
