# Generated by Django 4.2 on 2024-03-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_provider_meta_data_api_api_meta_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_history',
            name='email_body',
            field=models.TextField(default='Error Occured'),
        ),
        migrations.AddField(
            model_name='email_history',
            name='email_subject',
            field=models.TextField(default='Error Occured'),
        ),
    ]
