# Generated by Django 4.2 on 2024-02-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_archived_article_attribute_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archived_article_attribute',
            old_name='file_name',
            new_name='file_content',
        ),
    ]
