# Generated by Django 4.2 on 2024-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_rename_file_name_archived_article_attribute_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_meta_data_ftp',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='provider_model',
            name='delivery_method',
            field=models.CharField(choices=[('deposit', 'deposit'), ('FTP', 'FTP'), ('SFTP', 'SFTP'), ('API', 'API')], max_length=10),
        ),
    ]
