# Generated by Django 4.2 on 2024-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_alter_provider_meta_data_ftp_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_article_attribute',
            name='file_name_on_ftp',
        ),

        migrations.RemoveField(
            model_name='provider_model',
            name='deposit_path',
        ),
        migrations.RemoveField(
            model_name='provider_model',
            name='minimum_delivery_fq',
        ),
        migrations.RemoveField(
            model_name='provider_model',
            name='source_schema',
        ),
        migrations.AddField(
            model_name='archived_article_attribute',
            name='file_name_on_source',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='minimum_delivery_fq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider_meta_data_ftp',
            name='minimum_delivery_fq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
