# Generated by Django 4.2 on 2024-03-16 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_rename_file_name_on_ftp_archived_article_attribute_file_name_on_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_to', models.CharField(blank=True, max_length=50, null=True)),
                ('email_from', models.CharField(blank=True, max_length=50, null=True)),
                ('email_to', models.TextField(blank=True, null=True)),
                ('email_subject', models.TextField(default='Error Occured')),
                ('email_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='provider_model',
            name='delivery_method',
        ),
        migrations.AlterField(
            model_name='archived_article_attribute',
            name='file_name_on_source',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Fetch_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fetch_history', to='actions.provider_model')),
            ],
        ),
    ]
