# Generated by Django 4.2 on 2024-03-16 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_email_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=10)),
                ('email_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='email-notification', to='actions.email_notification')),
            ],
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='email_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='actions.email_history'),
        ),
    ]
