# Generated by Django 4.2 on 2024-03-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_email_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_notification',
            name='email_body',
            field=models.TextField(default='Error Occured'),
        ),
        migrations.AlterField(
            model_name='email_notification',
            name='email_from',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email_notification',
            name='email_to',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
