# Generated by Django 4.2 on 2024-03-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_alter_email_notification_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetch_history',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_meta_data_ftp',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fetch_history',
            name='status',
            field=models.CharField(default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_api',
            name='last_pull_status',
            field=models.CharField(default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_ftp',
            name='last_pull_status',
            field=models.CharField(default='success', max_length=10),
        ),
    ]
