# Generated by Django 4.2 on 2024-03-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_fetch_history_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_meta_data_api',
            name='email_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='actions.email_notification'),
        ),
    ]
