# Generated by Django 4.2 on 2024-03-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_alter_provider_meta_data_api_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='external_library_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='proxy_host_url',
            field=models.TextField(null=True),
        ),
    ]
