# Generated by Django 4.2 on 2024-03-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_provider_meta_data_api_external_library_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='is_paginated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='last_accessed_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='page_number',
            field=models.IntegerField(null=True),
        ),
    ]
