# Generated by Django 4.2 on 2024-03-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_provider_meta_data_api_is_token_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_article_attribute',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='actions.provider_model'),
        ),
        migrations.AlterField(
            model_name='archived_article_attribute',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('waiting', 'waiting'), ('processed', 'processed'), ('failed', 'failed')], max_length=12),
        ),
        migrations.AlterField(
            model_name='email_history',
            name='email_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='email_notification', to='actions.email_notification'),
        ),
    ]

