# Generated by Django 4.2 on 2024-03-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_alter_archived_article_attribute_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_article_attribute',
            name='unzipped_folder_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
