# Generated by Django 4.2 on 2024-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_authorization_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='menu',
            field=models.CharField(choices=[('provider-api-detail', 'provider-api-detail'), ('provider-ftp-detail', 'provider-ftp-detail'), ('provider-api-list', 'provider-api-list'), ('action-deposites', 'action-deposites'), ('archive-article-detail', 'archive-article-detail'), ('download-from-ftp', 'download-from-ftp'), ('articles-detail', 'articles-detail'), ('fetch-history-list', 'fetch-history-list'), ('unreadable-xml-files-list', 'unreadable-xml-files-list'), ('fetch-history-detail', 'fetch-history-detail'), ('unreadable-xml-files-detail', 'unreadable-xml-files-detail'), ('migrate-to-step2', 'migrate-to-step2'), ('download-from-crossref-api', 'download-from-crossref-api'), ('provider-deposite-list', 'provider-deposite-list'), ('download-from-chorus-api', 'download-from-chorus-api'), ('login', 'login'), ('provider-detail', 'provider-detail'), ('provider-list', 'provider-list'), ('archive-article-list', 'archive-article-list'), ('api-root', 'api-root'), ('provider-deposite-detail', 'provider-deposite-detail'), ('articles-list', 'articles-list'), ('download-from-sftp', 'download-from-sftp'), ('download-from-submission-api', 'download-from-submission-api'), ('logout', 'logout'), ('test_case', 'test_case'), ('provider-ftp-list', 'provider-ftp-list')], max_length=100),
        ),
    ]
