# Generated by Django 4.2 on 2025-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_authorization_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='menu',
            field=models.CharField(choices=[('action-deposites', 'action-deposites'), ('api-root', 'api-root'), ('archive-article-detail', 'archive-article-detail'), ('archive-article-list', 'archive-article-list'), ('articles-detail', 'articles-detail'), ('articles-list', 'articles-list'), ('download-from-chorus-api', 'download-from-chorus-api'), ('download-from-crossref-api', 'download-from-crossref-api'), ('download-from-ftp', 'download-from-ftp'), ('download-from-sftp', 'download-from-sftp'), ('download-from-submission-api', 'download-from-submission-api'), ('fetch-history-detail', 'fetch-history-detail'), ('fetch-history-list', 'fetch-history-list'), ('login', 'login'), ('logout', 'logout'), ('migrate-to-step-2', 'migrate-to-step-2'), ('provider-api-detail', 'provider-api-detail'), ('provider-api-list', 'provider-api-list'), ('provider-deposit-detail', 'provider-deposit-detail'), ('provider-deposit-list', 'provider-deposit-list'), ('provider-detail', 'provider-detail'), ('provider-ftp-detail', 'provider-ftp-detail'), ('provider-ftp-list', 'provider-ftp-list'), ('provider-list', 'provider-list'), ('unreadable-files-detail', 'unreadable-files-detail'), ('unreadable-files-list', 'unreadable-files-list')], max_length=100),
        ),
    ]
