# Generated by Django 4.2 on 2024-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_rename_last_stage_article_attributes_last_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='pull_switch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider_meta_data_ftp',
            name='pull_switch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='archive_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providers',
            name='article_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providers',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('deposit', 'deposit'), ('FTP', 'FTP'), ('SFTP', 'SFTP'), ('API', 'API')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='requirement_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providers',
            name='source_schema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='usda_source',
            field=models.BooleanField(default=False),
        ),
    ]
