# Generated by Django 4.2 on 2024-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_remove_archive_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_attributes',
            name='journal',
            field=models.FileField(blank=True, help_text='This field value will assigned automatically with the value assigned in article_file', null=True, upload_to=''),
        ),
    ]
