# Generated by Django 4.2 on 2024-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_alter_article_attributes_deposite_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadable_xml_files',
            name='source',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
