# Generated by Django 4.2 on 2024-08-15 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_alter_providers_last_time_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='next_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="This will be filled automatically base on minimum_delivery_frequency. Don't enter anything here"),
        ),
    ]
