# Generated by Django 4.2 on 2024-09-12 13:39

from django.db import migrations, models
import django.db.models.deletion
import model.article
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_alter_providers_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_attributes',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider', to='model.providers'),
        ),
        migrations.CreateModel(
            name='Jsonified_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_file', models.FileField(help_text='Browse the file', storage=model.article.OverWriteStorage(), upload_to=model.article.get_article_file_path)),
                ('journal', models.FileField(blank=True, help_text='This field value will assigned automatically with the value assigned in article_file', null=True, upload_to='')),
                ('title', models.TextField(blank=True, help_text='Article title', null=True)),
                ('type_of_record', models.CharField(choices=[('article', 'article'), ('retraction', 'retraction'), ('letter to the editor', 'letter to the editor')], help_text='Select from drop down', max_length=24)),
                ('last_step', models.IntegerField(default=3, help_text='Last stage article passed through 1-11')),
                ('last_status', models.CharField(choices=[('active', 'active'), ('failed', 'failed'), ('completed', 'completed')], default='active', help_text='Select from drop down', max_length=10)),
                ('note', models.TextField(default='ok', help_text='Note, warning or error note')),
                ('DOI', models.TextField(blank=True, help_text='A unique and persistent identifier', null=True)),
                ('PID', models.TextField(blank=True, help_text='A locally assign identifier', null=True)),
                ('MMSID', models.TextField(blank=True, help_text="The article's Alma identifer", null=True)),
                ('provider_rec', models.CharField(blank=True, help_text='Provider article identifier', max_length=10, null=True)),
                ('start_date', models.DateTimeField(auto_now=True, help_text='The date the article object was created')),
                ('current_date', models.DateTimeField(auto_now_add=True, help_text='The date finished the last stage')),
                ('end_date', models.DateTimeField(help_text='The data the article is staged for Alma', null=True)),
                ('deposite_path', models.TextField(default=pathlib.PureWindowsPath('E:/NAL-USDA/NAL_LIBRARY_SYSTEM/JSONIFIED_ARTICLES'))),
                ('article_attributes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_attribute', to='model.article_attributes')),
            ],
        ),
    ]
