# Generated by Django 4.2 on 2024-09-13 12:38

from django.db import migrations, models
import model.article


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_alter_article_attributes_provider_jsonified_articles'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='jsonified_articles',
        #     name='article_file',
        #     field=models.FileField(help_text='Browse the file', storage=model.article.OverWriteStorage(), upload_to=model.article.get_article_file_path),
        # ),
    ]
