# Generated by Django 4.2 on 2024-10-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_alter_archive_deposite_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider_meta_data_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(default='/', help_text='Enter path of source')),
                ('destination', models.TextField(help_text='Enter path of destination')),
                ('operation_type', models.CharField(choices=[('COPY', 'COPY'), ('MOVE', 'MOVE')], default='MOVE', help_text='Select if data will be moved or copied', max_length=10)),
                ('provider', models.ForeignKey(help_text='Select Provider name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='deposite_provider', to='model.providers')),
            ],
        ),
    ]
