# Generated by Django 4.2 on 2024-10-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_provider_meta_data_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='provider_type',
            field=models.CharField(choices=[('FTP', 'FTP'), ('API', 'API'), ('DEPOSIT', 'DEPOSIT')], default='FTP', max_length=8),
        ),
    ]
