# Generated by Django 4.2 on 2024-10-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_alter_providers_provider_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider_meta_data_deposit',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='provider_meta_data_deposit',
            name='operation_type',
        ),
        migrations.AlterField(
            model_name='providers',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('Deposite', 'Deposite'), ('FTP', 'FTP'), ('SFTP', 'SFTP'), ('API', 'API')], max_length=50, null=True),
        ),
    ]
