# Generated by Django 4.2 on 2024-11-27 15:44

from django.db import migrations, models
import django.db.models.deletion
import model.article


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_unreadable_files_delete_unreadable_xml_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_file', models.FileField(help_text='Browse the file', storage=model.article.OverWriteStorage(), upload_to=model.article.get_json_file_path)),
                ('journal', models.FileField(blank=True, help_text='This field value will assigned automatically with the value assigned in article_file', null=True, upload_to='')),
                ('title', models.TextField(blank=True, help_text='Article title', null=True)),
                ('type_of_record', models.CharField(choices=[('article', 'article'), ('retraction', 'retraction'), ('letter to the editor', 'letter to the editor')], help_text='Select from drop down', max_length=24)),
                ('last_step', models.IntegerField(default=3, help_text='Last stage article passed through 1-11')),
                ('last_status', models.CharField(choices=[('active', 'active'), ('failed', 'failed'), ('completed', 'completed')], default='active', help_text='Select from drop down', max_length=10)),
                ('note', models.TextField(default='ok', help_text='Note, warning or error note')),
                ('DOI', models.TextField(blank=True, help_text='A unique and persistent identifier', null=True)),
                ('PID', models.TextField(blank=True, help_text='A locally assign identifier', null=True)),
                ('MMSID', models.TextField(blank=True, help_text="The article's Alma identifer", null=True)),
                ('provider_rec', models.CharField(blank=True, help_text='Provider article identifier', max_length=10, null=True)),
                ('start_date', models.DateTimeField(auto_now=True, help_text='The date the article object was created')),
                ('current_date', models.DateTimeField(auto_now_add=True, help_text='The date finished the last stage')),
                ('end_date', models.DateTimeField(help_text='The data the article is staged for Alma', null=True)),
                ('record', models.TextField(blank=True, default='N/A', help_text='Path to pickle metadata record object')),
            ],
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='deposite_path',
            new_name='deposit_path',
        ),
        migrations.RenameField(
            model_name='article_attributes',
            old_name='deposite_path',
            new_name='deposit_path',
        ),
        migrations.AddField(
            model_name='article_attributes',
            name='record',
            field=models.TextField(blank=True, default='N/A', help_text='Path to pickle metadata record object'),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_deposit',
            name='provider',
            field=models.ForeignKey(help_text='Select Provider name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='deposit_provider', to='model.providers'),
        ),
        migrations.DeleteModel(
            name='Jsonified_articles',
        ),
        migrations.AddField(
            model_name='article',
            name='article_attributes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_attribute', to='model.article_attributes'),
        ),
    ]
