# Generated by Django 4.2 on 2025-01-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0024_remove_article_attributes_deposit_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_attributes',
            name='is_content_changed',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
