# Generated by Django 4.2 on 2025-01-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0025_remove_article_attributes_is_content_changed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_attributes',
            new_name='Article',
        ),
    ]
