# Generated by Django 4.2 on 2025-01-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0027_alter_article_provider_rec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='record',
            new_name='citation_pickle',
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_type',
            field=models.CharField(help_text='This field will store the extension of the file. For example .json, .xml, .zip etc', max_length=20),
        ),
    ]
