# Generated by Django 4.2 on 2025-01-30 11:56

from django.db import migrations, models
import model.article


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0028_rename_record_article_citation_pickle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='citation_pickle',
            field=models.FileField(help_text='This field will store citation article in pickel format as .pkl or .pickel file extension', storage=model.article.OverWriteStorage(), upload_to=model.article.get_pickel_file_path),
        ),
    ]
