# Generated by Django 4.2 on 2025-02-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0030_journal_alter_article_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='collection_status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('from_submission', 'from_submission'), ('rejected', 'rejected')], help_text='Select available collection status from the drop down', max_length=16),
        ),
        migrations.AlterField(
            model_name='journal',
            name='harvest_source',
            field=models.CharField(blank=True, help_text='Harvest Source', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, help_text='ISSN Number', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_title',
            field=models.CharField(blank=True, help_text='Journal Title', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='local_id',
            field=models.CharField(blank=True, help_text='Local ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mmsid',
            field=models.CharField(blank=True, help_text='Local ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='note',
            field=models.CharField(blank=True, help_text='Any error msg or important msg to be assigned', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher Code', max_length=256, null=True),
        ),
    ]
