# Generated by Django 4.2 on 2025-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0032_alter_article_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='collection_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('from_submission', 'from_submission'), ('rejected', 'rejected')], help_text='Select available collection status from the drop down', max_length=16, null=True),
        ),
    ]
