# Generated by Django 4.2 on 2025-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0033_alter_journal_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, help_text='ISSN Number', max_length=100, null=True),
        ),
    ]
