# Generated by Django 4.2 on 2025-02-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0034_alter_journal_issn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='local_id',
        ),
        migrations.AddField(
            model_name='journal',
            name='doi',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='journal',
            name='nal_journal_id',
            field=models.CharField(blank=True, help_text='Local ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='requirement_override',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='journal',
            name='subject_cluster',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(default=None, help_text='This field value will assigned automatically with journal id as received from jounral info in step 4', max_length=15),
        ),
    ]
