# Generated by Django 4.2 on 2025-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0035_remove_journal_local_id_journal_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(default=None, help_text='This field value will assigned automatically with journal id as received from jounral info in step 4', max_length=15, null=True),
        ),
    ]
