# Generated by Django 4.2 on 2025-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0036_alter_article_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='doi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='requirement_override',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='subject_cluster',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
