# Generated by Django 4.2 on 2024-05-25 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_to', models.TextField(help_text='Enter any name to indentify where this record will be used as foreign key for sending email')),
                ('email_from', models.TextField(help_text='Enter email address of the sender')),
                ('email_to', models.TextField(help_text='Enter list of email addresses of the receivers in this format email-1;email-2;email3;and so on;')),
                ('email_subject', models.TextField(default='Error Occured', help_text='Email default subject')),
                ('email_body', models.TextField(blank=True, help_text='Email body. This will be the error message from the exceptions handlers', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=10)),
                ('email_subject', models.TextField(default='Error Occured')),
                ('email_body', models.TextField(default='Error Occured')),
                ('email_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='email_notification', to='mail_service.email_notification')),
            ],
        ),
    ]
