# Generated by Django 4.2 on 2024-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file_name_on_source',
            field=models.CharField(blank=True, help_text='File name for FTP will be assigned automatically as received. For API                                             No file name is received hence file name will be saved as DOI.json', max_length=500, null=True),
        ),
    ]
