# Generated by Django 4.2 on 2024-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_archive_file_name_on_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_meta_data_api',
            name='last_pull_status',
            field=models.CharField(default='success', help_text="For the first time enter 'Initial'. This field will maintain last sync status success or failed", max_length=10),
        ),
        migrations.AlterField(
            model_name='provider_meta_data_ftp',
            name='last_pull_status',
            field=models.CharField(default='success', help_text="For the first time enter 'Initial'. This field will maintain last sync status success or failed", max_length=10),
        ),
    ]
