# Generated by Django 4.2 on 2024-06-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_provider_meta_data_api_last_pull_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_attributes',
            old_name='last_stage',
            new_name='last_step',
        ),
    ]
