# Generated by Django 4.2 on 2024-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_article_attributes_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadable_xml_files',
            name='date_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
