# Generated by Django 4.2 on 2024-07-25 07:57

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_unreadable_xml_files_date_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_attributes',
            name='deposite_path',
            field=models.TextField(default=pathlib.PureWindowsPath('E:/NAL-USDA/NAL_LIBRARY_SYSTEM/ARTICLES')),
        ),
    ]
