# Generated by Django 4.2 on 2024-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_unreadable_xml_files_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_attributes',
            name='PID',
            field=models.TextField(blank=True, help_text='A locally assign identifier', null=True),
        ),
    ]
